config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
  resources :products
  resources :logos do
    post 'rename', on: :collection
    collection do
      get 'get'
      get 'app'
      get 'logo_data'
    end
  end
  resources :colors do
    collection do
      get 'pass'
      get 'logofromcolor'
      get 'new2'
      get 'indexx'
      get 'test'
      get 'appz'
      get 'components'
    end
  end

  # resources :cart, only: [:show, :add, :remove] do
  #   collection do
  #     get :toggle
  #   end
  # end  

  get 'tester' => 'application#tester'

  get 'pass' => 'colors#pass'
  get 'colors_and_logos', to: 'colors_and_logos#index'
  get 'testpr' => 'products#testpr'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  root 'products#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum { |orderable| orderable.total }
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find(params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)

    if current_orderable && quantity > 0
      current_orderable.update(quantity: quantity)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity: quantity)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart', partial: 'cart/orderables', locals: { cart: @cart })
      end
      format.html { redirect_to cart_path }
    end
  end

  def remove
    Orderable.find(params[:id]).destroy

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('cart', partial: 'cart/orderables', locals: { cart: @cart })
      end
      format.html { redirect_to cart_path }
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <p>Totalc1: <%= usd(@cart.total) %></p>
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
    <p class="mt-4 text-lg font-semibold">Totalc: <%= usd(@cart.total) %></p>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
<% end %>

app/views/cart/_orderables.html.erb
<!-- orderables.html.erb -->
<%= turbo_frame_tag "cart" do %>
<div class="space-y-2">
  <% @cart.orderables.order(:id).each do |orderable| %>
    <% product = orderable.product %>
    <div class="border border-gray-300 p-2 rounded-md flex flex-col space-y-1">
      <%= image_tag asset_path("products/#{product.image}"), class: "w-full h-24 object-cover mb-1 rounded-md" %>
      <div class="text-sm mb-1"><%= product.name %></div>
      <div class="text-xs mb-1"><%= usd(product.price) %></div>
      <%= form_with(url: cart_add_path, local: true) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <%= f.number_field :quantity, value: orderable.quantity, min: 0, max: 99, class: "quantity-field text-center w-full mb-1 border rounded-md p-1 text-sm" %>
        <%= f.submit "Update", class: "bg-blue-500 text-white py-1 px-2 w-full mb-1 rounded-md text-sm" %>
      <% end %>
      <div class="flex justify-between items-center">
        <%= form_with(url: cart_remove_path) do |f| %>
          <%= f.hidden_field :id, value: orderable.id %>
          <%= f.submit "X", class: "bg-red-500 text-white py-1 px-2 w-8 h-8 rounded-full text-xs flex items-center justify-center" %>
        <% end %>
        <p class="text-sm"><strong>Totalo:</strong> <%= usd(orderable.total) %></p>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/cart/_total.html.erb
<p class="mt-4 text-lg font-semibold">Total: <%= usd(@cart.total) %></p>

app/views/cart/show.html.erb
<h1>Cart#show</h1>
<p>Find me in app/views/cart/show.html.erb</p>

<%= render "cart/orderables" %>