config/routes.rb
Rails.application.routes.draw do
  get 'cart/show'
  resources :products
  resources :logos do
    post 'rename', on: :collection
    collection do
      get 'get'
      get 'app'
      get 'logo_data'
    end
  end
  resources :colors do
    collection do
      get 'pass'
      get 'logofromcolor'
      get 'new2'
      get 'indexx'
      get 'test'
      get 'appz'
      get 'components'
    end
  end

  # resources :cart, only: [:show, :add, :remove] do
  #   collection do
  #     get :toggle
  #   end
  # end  

  get 'tester' => 'application#tester'

  get 'pass' => 'colors#pass'
  get 'colors_and_logos', to: 'colors_and_logos#index'
  get 'testpr' => 'products#testpr'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  root 'products#index'
end

app/models/logo.rb
class Logo < ApplicationRecord
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: %i[ show edit update destroy ]

    @passeda ='JHAJHKJHS'

    def get
    item = {
    "1" => "hello",
    "2" => "world",
    }[params[:item_id]]

    # render json: { item: item }, status: 200
    p 'KJHAJKSHKJAHSJKSHJKHSKJSHAKJSHKJAHSAKJHSKJHASKJHSKJSHKJASHAJKSHJKSHJ'
    puts item
    @passed_var = 'hKJKJHKJHKH'
    @passed_two = item
    puts @passed_two
    render pass_colors_path
  end

  def app
    $aaa = "#{Rails.root}/app/assets/images/logo"
    dir_path = "#{Rails.root}/app/assets/images/logo"
    @dpath = "#{Rails.root}/app/assets/images/logo"
    @images = Dir.entries(dir_path).select { |f| File.file?("#{dir_path}/#{f}") }

    # Debugging
    puts "Directory Path: #{dir_path}"
    puts @dpath
    puts "Files in Directory: #{@images}"
    puts @logo_data

    @logo_data = @images.map do |image|
      {
        name: File.basename(image, File.extname(image)),
        file: image,
        path: @dpath,
        #image_tag: ActionController::Base.helpers.image_tag("logo/#{image}", class: 'img-1', size: '100x100')
        #url: ActionController::Base.helpers.image_path("logo/#{image}") # Add image URL
      }
    end

    respond_to do |format|
      format.json { render json: app }
      format.html {render :app}
    end

  end

  def passtologo
    @passeda ='JHAJHKJHS'
    dir_path = "#{Rails.root}/app/assets/images/logo"
    @dpath = "#{Rails.root}/app/assets/images/logo"
    @images = Dir.entries(dir_path).select { |f| File.file?("#{dir_path}/#{f}") }
    @logo_data = @images.map do |image|
      {
        name: File.basename(image, File.extname(image)),
        file: image,
        path: @dpath,
      }
    end

    # ColorsController.instance_variable_get(:@comesfrom)
    # p @comesfrom
    # #if ColorsController.instance_variable_get(:@comesfrom) == "pass"
    
    # if @comesfrom == "pass"
      render pass_colors_path
    # end

    #@logo_data
  end



  # New action to respond to JSON fetch request
  def logo_data
    #@passeda ='JHAJHKJHS'
    dir_path = "#{Rails.root}/app/assets/images/logo"
    @dpath = "#{Rails.root}/app/assets/images/logo"
    @images = Dir.entries(dir_path).select { |f| File.file?("#{dir_path}/#{f}") }

    @logo_data = @images.map do |image|
      {
        name: File.basename(image, File.extname(image)),
        file: image,
        path: @dpath,
        #image_tag: ActionController::Base.helpers.image_tag("logo/#{image}", class: 'img-1', size: '100x100')
        #url: ActionController::Base.helpers.image_path("logo/#{image}") # Add image URL
      }
    end

    # ColorsController.instance_variable_get(:@comesfrom)
    # p @comesfrom
    # #if ColorsController.instance_variable_get(:@comesfrom) == "pass"
    
    # if @comesfrom == "pass"
      # render pass_colors_path
    # end

    #@logo_data
    respond_to do |format|
      format.json { render json: @logo_data }
      format.html {render :logo_data}
    end
  end

  def rename
    @rw = params[:rw]
    old_name = params[:old_name]
    new_name = params[:new_name]

    Rails.logger.info("Received params: rw=#{@rw}, dpath=#{@dpath}, old_name=#{old_name}, new_name=#{new_name}")

    # THIS BELOW CODE SEGMENT MADE IT WORK AGAIN **VERY IMPORTANT**
    # Check if paths are valid
    if $aaa.nil? 
      Rails.logger.error("dpath or old_name or new_name is nil aaa is #{$aaa}")
      redirect_to app_logos_path, alert: "Error: Missing required parameters."
      return
    end    

    if old_name.present? && new_name.present?
      old_path = File.join($aaa, "#{old_name}.png")
      new_path = File.join($aaa, "#{new_name}.png")

      Rails.logger.info("Old path: #{old_path}")
      Rails.logger.info("New path: #{new_path}")

      if File.exist?(old_path)
        File.rename(old_path, new_path)
        puts "#{old_name} has been renamed with params #{@rw}: #{new_name}"
      else
        Rails.logger.error("File not found at #{old_path}")
      end
    else
      Rails.logger.error("Both old_name and new_name must be present")
    end
    puts @rw
    if @rw == "colors" || @rw == "1"
      redirect_to logofromcolor_colors_path, notice: "File Renamed. #{old_name} has been renamed with params #{@rw}: #{new_name}"
    else
      redirect_to app_logos_path, notice: "File Renamed. #{old_name} has been renamed with params #{@rw}: #{new_name}"
    end
  end


  # GET /logos or /logos.json
  def index
    @logos = Logo.all
    @colors = Color.all
    @thiscol = Color.find(1)
    puts @thiscol.inspect
  end

  # GET /logos/1 or /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos or /logos.json
  def create
    @logo = Logo.new(logo_params)

    respond_to do |format|
      if @logo.save
        format.html { redirect_to logo_url(@logo), notice: "Logo was successfully created." }
        format.json { render :show, status: :created, location: @logo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1 or /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to logo_url(@logo), notice: "Logo was successfully updated." }
        format.json { render :show, status: :ok, location: @logo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1 or /logos/1.json
  def destroy
    @logo.destroy!

    respond_to do |format|
      format.html { redirect_to logos_url, notice: "Logo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def logo_params
      params.require(:logo).permit(:name, :img)
    end
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/views/logos/_form.html.erb
<%= form_with(model: logo) do |form| %>
  <% if logo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
        <% logo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :img, style: "display: block" %>
    <%= form.text_field :img %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/logos/_logo.html.erb
<div id="<%= dom_id logo %>">
  <p>
    <strong>Name:</strong>
    <%= logo.name %>
  </p>

  <p>
    <strong>Img:</strong>
    <%= logo.img %>
  </p>

</div>

app/views/logos/app.html copy.erb
<script>
  let jjj = "a"
  let jslogo = '<%= @images %>'
  let jsd = '<%= @logo_data[0][:name] %>'
</script>
aapp
<button class="btn btn-primary">cool button</button>

<!-- app/views/logos/index.html.erb -->
<h1>Default Logos</h1>

<% @logo_data.each do |logo| %>
  <div class="logo">
    <h2>Name: <%= logo[:name] %></h2>
    <p>File: <%= logo[:file] %></p>
<!-- Set the src attribute dynamically -->
    <%= image_tag("logo/#{logo[:file]}", class: 'img-1', size: 100 ) %>
  </div>
<% end %>

app/views/logos/app.html.erb
<script>
  let jjj = "a"
  let jslogo = '<%= @images %>'
  let jsd = '<%= @logo_data[0][:name] %>'
</script>
App
<%= @globvar %>
<%= asset_path('crew_front.png') %>
<%= @logo_data %>
<!-- app/views/logos/index.html.erb -->
<h1>Default Logos</h1>

<% @logo_data.each do |logo| %>
  <div class="logo">
    <h2>Name: <%= logo[:name] %></h2>
    <p>File: <%= logo[:file] %></p>
    <!-- Set the src attribute dynamically -->
    <%= image_tag("logo/#{logo[:file]}", class: 'img-1', size: 100 ) %>

    <!-- Form for renaming -->
    <%= form_with(url: rename_logos_path, method: :post) do |form| %>
      <%= form.hidden_field :dpath, value: @dpath %>
      <%= form.hidden_field :old_name, value: logo[:name] %>
      <%= form.label :new_name, 'New Name:' %>
      <%= form.text_field :new_name %>
      <%= form.submit 'Rename' %>
    <% end %>
  </div>
<% end %>

app/views/logos/edit.html.erb
<h1>Editing logo</h1>

<%= render "form", logo: @logo %>

<br>

<div>
  <%= link_to "Show this logo", @logo %> |
  <%= link_to "Back to logos", logos_path %>
</div>

app/views/logos/get.html.erb
get

app/views/logos/index.html.erb
<p style="color: green"><%= notice %></p>
<%= @thiscol.inspect %>
<h1>Logos</h1>

<div id="logos">
  <% @colors.each do |colorz| %>
    <%= render colorz %>
    <%= colorz.name.inspect %>
    <p>
      <%#= link_to "Show this logo", logo %>
    </p>
  <% end %>
</div>

<h1>Logos</h1>

<div id="logos">
  <% @logos.each do |logo| %>
    <%= render logo %>
    <p>
      <%= link_to "Show this logo", logo %>
    </p>
  <% end %>
</div>

<%= link_to "New logo", new_logo_path %>

<img src="C:/dev/project/_html/shirtman/img/crew_front.png">

app/views/logos/logo_data.html.erb
<script>
  let jjj = "a"
  let jslogo = '<%= @images %>'
  let jsd = '<%= @logo_data[0][:name] %>'
</script>
App
<%= @globvar %>
<%= asset_path('crew_front.png') %>
<%= @logo_data %>
<!-- app/views/logos/index.html.erb -->
<h1>Default Logos</h1>

<% @logo_data.each do |logo| %>
  <div class="logo">
    <h2>Name: <%= logo[:name] %></h2>
    <p>File: <%= logo[:file] %></p>
    <!-- Set the src attribute dynamically -->
    <%= image_tag("logo/#{logo[:file]}", class: 'img-1', size: 100 ) %>

    <!-- Form for renaming -->
    <%= form_with(url: rename_logos_path, method: :post) do |form| %>
      <%= form.hidden_field :rw, value: 1 %>
      <%= form.hidden_field :dpath, value: @dpath %>
      <%= form.hidden_field :old_name, value: logo[:name] %>
      <%= form.label :new_name, 'New Name:' %>
      <%= form.text_field :new_name %>
      <%= form.submit 'Rename' %>
    <% end %>
  </div>
<% end %>

app/views/logos/new.html.erb
<h1>New logo</h1>

<%= render "form", logo: @logo %>

<br>

<div>
  <%= link_to "Back to logos", logos_path %>
</div>

app/views/logos/show.html.erb
<!--
<p style="color: green"><%= notice %></p>

<%= render @logo %>

<div>
  <%= link_to "Edit this logo", edit_logo_path(@logo) %> |
  <%= link_to "Back to logos", logos_path %>

  <%= button_to "Destroy this logo", @logo, method: :delete %>
</div>
-->